### ISSUE TITLE
Remove homophobic text from example

### ISSUE THREAD

**Issue by alanb1501** [dsc/jsongrep#1]
In the example, there is homophobic text. Remove it.

**Comment by dsc** [comment]
A very good point. I literally issued the CURL to the Twitter API and didn't really read the results. Kindly blame the horrors of humanity.

**Comment by dsc** [comment]
It's actually a sad comment on both humans and (ahem) our attentional allocations that his went unnoticed until recently.

**Comment by alanb1501** [comment]
Cheers.
